version: '3.7'

services:
  cheesey-bingo-api
    container_name: cheesey-bingo-api
    restart: always
    build: .
    environment:
      PORT: 80
      PUBLIC_URL: https://api.cheeseybingo.co.uk
      VIRTUAL_HOST: api.cheeseybingo.co.uk
      LETSENCRYPT_HOST: api.cheeseybingo.co.uk
      LETSENCRYPT_EMAIL: hello@jackallen.me
    expose:
      - 80
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
